### ISSUE TITLE
jsondecode not in older versions of matlab

### ISSUE THREAD

**Issue by jsbenjamins** [dcnieho/GlassesViewer#2]
Hey D, yes I know I should update my Matlab perhaps, but the jsondecode is not available in R2014a... any ideas to circumvent it?

**Comment by dcnieho** [comment]
Ha Jeroen. Hmm, that sucks. any jsondecoder on matlab FEX?

Cheers,
Dee

**Comment by dcnieho** [comment]
using matlab.internal.webservices.fromJSON, we now support back to R2015b (I think). Think that's enough, i won't be testing on older versions anyway.
