### ISSUE TITLE
GlassesViewer requires eye video

### ISSUE THREAD

**Issue by royhessels** [dcnieho/GlassesViewer#4]
After updating to latest Firmware version, GlassesViewer seems to crash upon reading a recording *without* eye videos turned on (see screenshot for error).

<img width="522" alt="screen shot 2018-09-14 at 11 41 03" src="https://user-images.githubusercontent.com/18262509/45542817-3a7d9c00-b813-11e8-81eb-0353f698042d.png">

Loading recordings with eye videos works normally.

**Comment by dcnieho** [comment]
Thats already been fixed two weeks ago or so, please pull the latest version
