### ISSUE TITLE
Where can I find my data?

### ISSUE THREAD

**Issue by shp0929** [dcnieho/GlassesViewer#9]
Hi,

I am a PhD student in New Zealand. I recently downloaded the GlassesViewer and GazeCode to use with Tobii Pro Glasses 3.

I have read your article and the manual on github. And I am currently trying out the demos. I was able to do everything except:
1) find my data from GlassesViewer and GazeCode (see image attached below). 
![image](https://user-images.githubusercontent.com/95594455/144965494-b2fab465-073a-4caa-a84c-15b5e1caab3e.png)

2) how to upload my own video recording to GlassesViewer. When I record videos using Tobii Pro Glasses 3, files I get in my SD card looks like this (see images below). I am not really sure how I can organise/convert these files so I can upload it to GlassesViewer. 
![image](https://user-images.githubusercontent.com/95594455/144965647-c5aa6099-bde1-42ef-af8a-a52143865d2b.png)
![image](https://user-images.githubusercontent.com/95594455/144965676-e119d9c4-5df8-4e7a-af2b-0de4b9280a1d.png)
![image](https://user-images.githubusercontent.com/95594455/144965700-cc6583fc-6500-45fb-bba2-afa3a5135dc8.png)

I am sorry if it's a question that has already been answered. I unfortunately do not have any zero coding experience. Thank you so much for your time and than you very much for developing GlassesViewer. 

Best regards,
So Hyun Park

**Comment by dcnieho** [comment]
Thanks for your interest!

1. After opening the recording in glassesViewer, the data will be two
folders up from where you're looking (so in gzz7stc in this case).
2. Glasses 3 is not supported yet. I have made a start a year ago, but that
version of the glasses was too early, it didn't support everything you'd
want to have yet. If you can send me a recording with the latest firmware
to my work email address, i can have a look into adding support.

**Comment by dcnieho** [comment]
Glasses 3 support is now finished, update to use it. Closing due to lack of feedback.
